.MODEL SMALL
.STACK 64
.DATA
 MSG1 DB "QUANTITY (UNIT): $"
 MSG2 DB 13,10,"UNIT PRICE (RM): $"
 MSG3 DB 0DH,0AH,"TOTAL AMOUNT IS RM$"
 QTY DB 0
 PRI DB 0
 TTL DB 0
.CODE
MAIN PROC
 MOV AX,@DATA
 MOV DS,AX
 
 ;--OUTPUT STRING:09H(MSG1)
 MOV AH,09H
 LEA DX,MSG1
 INT 21H

 ;--INPUT BYTE:01H
 MOV AH,01H
 INT 21H

 ;--MOVE USER INPUT(AL) TO QTY
 MOV QTY,AL

 ;------------------------------
 ;--OUTPUT STRING:09H(MSG2)
 MOV AH,09H
 LEA DX,MSG2
 INT 21H

 ;--INPUT BYTE:01H
 MOV AH,01H
 INT 21H

 ;--MOVE USER INPUT(AL) TO PRI
 MOV PRI,AL

 ;------------------------------
 ;--CALCULATION
 ;--1)CLEAR AX
 MOV AX,0
 ;--2)CONVERT HEX TO DEC:QTY,PRI
 SUB QTY,30H
 SUB PRI,30H
 ;--3)MOVE MULTIPLICAND(QTY) TO AL
 MOV AL,QTY
 ;--4) MULTIPLY BY MULTIPLIER(PRI)
 MUL PRI 
 ;--5)MOVE RESULT(AL) TO TTL
 MOV TTL,AL
 ;--6)CONVERT DEC TO HEX:TTL
 ADD TTL,30H
 
 ;------------------------------
 ;--OUTPUT STRING:09H(MSG3)
 MOV AH,09H
 LEA DX,MSG3
 INT 21H

 ;--OUTPUT BYTE:02H(TTL)
 MOV AH,02H
 MOV DL,TTL
 INT 21H


 MOV AH,4CH
 INT 21H
MAIN ENDP
 END MAIN