.MODEL SMALL
.STACK 64
.DATA
 MSG DB "SUM: $"
 ITEM1 DB 1,2,3,2,1
 TTL DB 0
.CODE
MAIN PROC
 MOV AX,@DATA
 MOV DS,AX

 ;-OUTPUT STRING:09H(MSG)
 MOV AH,09H
 LEA DX,MSG 
 INT 21H

 ;-CALCULATION
 ;-CLEAR AX
 MOV AX,0
 ;-ADD SUCCESSIVELY
 MOV SI,0        ;SI=0
 MOV CX,5        ;CX=5
 CALC:
  ADD AL,ITEM1[SI] ;AL=1
  INC SI           ; SAME AS ADD  SI,1
  LOOP CALC        ;CX=4
                     

 ;-MOVE RESULT (AL) TO TTL
 MOV TTL,AL

 ;CONVERT DEC TO HEX
 ADD TTL,30H

 ;-OUTPUT BYTE:02H(TTL)
 MOV AH,02H
 MOV DL,TTL
 INT 21H

 MOV AH,4CH
 INT 21H
MAIN ENDP
 END MAIN