.MODEL SMALL
.STACK 64
.DATA
 VAR1 DB "COMPUTER"
 VAR2 DB 8 DUP('*')
 MSG1 DB "1.ORIGINAL$"
 MSG2 DB 13,10,"2.AFTER EXCHANGE$"
 MSG3 DB 13,10,"3.AFTER CHANGE CASE$"
 MSG4 DB 13,10,"4.AFTER REVERSE$"
 MSGV1 DB 13,10,"VAR1 = $"
 MSGV2 DB 13,10,"VAR2 = $"
.CODE
MAIN PROC
 MOV AX,@DATA
 MOV DS,AX
 
 ;-OUTPUT STRING:09H(MSG1)
 MOV AH,09H
 LEA DX,MSG1
 INT 21H

 ;-OUTPUT STRING:09H(MSGV1)
 MOV AH,09H
 LEA DX,MSGV1
 INT 21H

 ;-OUTPUT BYTE:02H(VAR1[SI])
 MOV SI,0
 MOV CX,8
 PRINTV1:
  MOV AH,02H
  MOV DL,VAR1[SI]
  INT 21H
  INC SI
  LOOP PRINTV1



 ;-OUTPUT STRING:09H(MSGV2)
 MOV AH,09H
 LEA DX,MSGV2
 INT 21H 

 ;-OUTPUT BYTE:02H(VAR2[SI])
 MOV SI,0
 MOV CX,8
 PRINTV2:
  MOV AH,02H
  MOV DL,VAR2[SI]
  INT 21H
  INC SI
  LOOP PRINTV2

 ;----------------------------------
 ;EXCHANGE

 ;-OUTPUT STRING:09H(MSG2)
 MOV AH,09H
 LEA DX,MSG2
 INT 21H

 ;-OUTPUT STRING:09H(MSGV1)
 MOV AH,09H
 LEA DX,MSGV1
 INT 21H

 ;-EXCHANGE
 MOV SI,0
 MOV CX,8
 EXCHG:
  MOV AL,VAR1[SI]
  XCHG AL,VAR2[SI]
  MOV VAR1[SI],AL
  INC SI
  LOOP EXCHG

 ;-OUTPUT BYTE:02H(VAR1[SI])
 MOV SI,0
 MOV CX,8
 PRINTV1EX:
  MOV AH,02H
  MOV DL,VAR1[SI]
  INT 21H
  INC SI
  LOOP PRINTV1EX

 
 ;-OUTPUT STRING:09H(MSGV2)
 MOV AH,09H
 LEA DX,MSGV2 
 INT 21H
 ;-OUTPUT BYTE:02H(VAR2[SI])
 MOV SI,0
 MOV CX,8
 PRINTV2EX:
  MOV AH,02H
  MOV DL,VAR2[SI]
  INT 21H
  INC SI
  LOOP PRINTV2EX

 ;----------------------------------
 ;CHANGE CASE

 ;-OUTPUT STRING:09H(MSG3)
 MOV AH,09H
 LEA DX,MSG3
 INT 21H

 ;-LOAD COMPUTER INTO VAR1
 MOV SI,0
 MOV CX,8
 LOAD:
  MOV AL,VAR2[SI]
  MOV VAR1[SI],AL
  INC SI
  LOOP LOAD

 ;-CHANGE CASE
 MOV SI,0
 MOV CX,8
 CHGCASE:
 ADD VAR2[SI],20H
 INC SI
 LOOP CHGCASE 

 ;-OUTPUT STRING:09H(MSGV1)
 MOV AH,09H
 LEA DX,MSGV1
 INT 21H

 ;-OUTPUT BYTE:02H(VAR1[SI])
 MOV SI,0
 MOV CX,8
 PRINTV1CASE:
  MOV AH,02H
  MOV DL,VAR1[SI]
  INT 21H
  INC SI
  LOOP PRINTV1CASE

 ;-OUTPUT STRING:09H(MSGV2)
 MOV AH,09H
 LEA DX,MSGV2
 INT 21H 

 ;-OUTPUT BYTE:02H(VAR2[SI])
 MOV SI,0
 MOV CX,8
 PRINTV2CASE:
  MOV AH,02H
  MOV DL,VAR2[SI]
  INT 21H
  INC SI
  LOOP PRINTV2CASE

 ;------------------------------------
 ;REVERSE
 ;-OUTPUT STRING:09H(MSG4)
 MOV AH,09H
 LEA DX,MSG4
 INT 21H

 ;-REVERSE
 MOV SI,7
 MOV DI,0
 MOV CX,8
 REVERSE:
  MOV AL,VAR1[SI]
  MOV VAR2[DI],AL
  SUB SI,1
  INC DI
  LOOP REVERSE

 ;-OUTPUT STRING:09H(MSGV1)
 MOV AH,09H
 LEA DX,MSGV1
 INT 21H

 ;-OUTPUT BYTE:02H(VAR1[SI])
 MOV SI,0
 MOV CX,8
 PRINTV1REVERSE:
  MOV AH,02H
  MOV DL,VAR1[SI]
  INT 21H
  INC SI
  LOOP PRINTV1REVERSE

 ;-OUTPUT STRING:09H(MSGV2)
 MOV AH,09H
 LEA DX,MSGV2
 INT 21H 

 ;-OUTPUT BYTE:02H(VAR2[SI])
 MOV SI,0
 MOV CX,8
 PRINTV2REVERSE:
  MOV AH,02H
  MOV DL,VAR2[SI]
  INT 21H
  INC SI
  LOOP PRINTV2REVERSE


 MOV AH,4CH
 INT 21H
MAIN ENDP
 END MAIN