.MODEL SMALL
.STACK 64
.DATA
 UNAME DB "BACS"
 UPSW DB "1024"
 MSG1 DB 13,10,"USERNAME: $"
 INAME DB 4 DUP(0)
 MSG2 DB 13,10,"PASSWORD: $"
 IPSW DB 4 DUP(0)
 IMSG DB 13,10,"INVALID LOGIN!$"
 VMSG DB 13,10,"ACCESS GRANTED!$"
 COUNT DB 0 
.CODE
MAIN PROC
 MOV AX,@DATA
 MOV DS,AX
 START:
    ;-OUTPUT STRING:09H(MSG1)
    MOV AH,09H 
    LEA DX,MSG1 
    INT 21H
    ;-INPUT BYTE:01H, MOVE INPUT(AL) TO INAME[SI],LOOP
    MOV SI,0 
    MOV CX,4
    GETNAME:
    MOV AH,01H 
    INT 21H 
    MOV INAME[SI],AL 
    INC SI 
    LOOP GETNAME

    ;-OUTPUT STRING:09H(MSG2)
    MOV AH,09H 
    LEA DX,MSG2
    INT 21H
    ;-INPUT BYTE:01H, MOVE INPUT(AL) TO IPSW[SI],LOOP
    MOV SI,0 
    MOV CX,4
    GETPSW:
    MOV AH,01H 
    INT 21H
    MOV IPSW[SI],AL 
    INC SI 
    LOOP GETPSW

 MOV SI,0 
 MOV DI,0 
 CHKNAME:
  CMP SI,4 
  JE CHKPSW 
  MOV AL,INAME[SI]
  CMP UNAME[SI],AL 
  JE NXTNAME
  JNE ERROR

 NXTNAME:
  INC SI
  JMP CHKNAME

 CHKPSW:
  CMP DI,4 
  JE WELCOME
  MOV AL,IPSW[DI]
  CMP IPSW[DI],AL 
  JE NXTPSW
  JNE ERROR

 NXTPSW:
  INC DI
  JMP CHKPSW 

 ERROR:
  MOV AH,09H 
  LEA DX,IMSG 
  INT 21H
  INC COUNT 
  CMP COUNT,3
  JE EXIT
  JNE START

 WELCOME: 
  MOV AH,09H 
  LEA DX,VMSG 
  INT 21H
  JMP START

 EXIT:
 MOV AH,4CH
 INT 21H
MAIN ENDP
 END MAIN